import type { Metadata } from "next";
import { requireAgent } from "@/lib/agent-auth";
import { getDraftArticles } from "@/lib/article-queue";
import { ArticleReviewForm } from "@/components/article-review-form";

export const metadata: Metadata = {
  title: "Articles — LEVR Auto Internal",
};

export const dynamic = "force-dynamic";

export default async function InternalArticlesPage() {
  const agent = await requireAgent();
  const drafts = await getDraftArticles();

  return (
    <section className="min-h-screen bg-zinc-950 py-16">
      <div className="mx-auto max-w-4xl px-6">
        <h1 className="text-2xl font-semibold text-white">Articles</h1>
        <p className="mt-1 text-sm text-zinc-400">
          Signed in as {agent.name} ({agent.email})
        </p>
        <p className="mt-1 text-sm text-zinc-500">
          Drafts generated by the auto-draft cron, awaiting review. Nothing here ever goes live on
          its own — approving is the only way an article publishes.
        </p>

        <div className="mt-10 space-y-8">
          {drafts.length === 0 ? (
            <p className="text-sm text-zinc-500">No drafts awaiting review right now.</p>
          ) : (
            drafts.map((draft) => <ArticleReviewForm key={`${draft.id}:${draft.updatedAt}`} article={draft} />)
          )}
        </div>
      </div>
    </section>
  );
}
